name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        id: title_check
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            
            if (title !== "orange") { 
              core.setFailed(`Failed`)
            }
      - name: Echo Actor Name
        if: success()
        run: echo "The PR was created by ${{ steps.title_check.outputs.actor }}" 