name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            // Pattern matches [OMNICAB-<numbers>] or [n/a] at start of title
            const pattern = /^\[(OMNICAB-\d+|n\/a)\]/;
            
            if (!pattern.test(title)) {
              core.setFailed(`PR title "${title}" does not match the required pattern.
                Title must start with either [OMNICAB-<number>] or [n/a]
                Examples: 
                - [OMNICAB-12345] A jira ticket number
                - [n/a] No jira ticket number`);
            } else {
              core.success(`Hey ${context.actor}, you are doing great!`);
            }