name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            
            if (title !== "orange") { 
              core.setFailed(`Failed`)
            } else {
              core.setOutput(`Hey ${context.actor}, you are doing great!`);
            }