name: POM Version Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if project version was modified
        run: |
          # Debug git status
          echo "=== Git Status ==="
          git status
          
          echo "=== Git Branch Info ==="
          git branch -a
          
          # Get the diff between base branch and PR
          echo -e "\n=== Fetch Information ==="
          echo "Fetching base branch ${{ github.base_ref }}..."
          git fetch origin ${{ github.base_ref }}
          
          echo -e "\n=== Debug Information ==="
          echo "Base branch: ${{ github.base_ref }}"
          echo "PR commit: ${{ github.sha }}"
          echo "PR branch: ${{ github.head_ref }}"
          
          echo -e "\n=== POM Content Check ==="
          echo "Current POM version line:"
          grep "<version>" pom.xml || echo "No version tag found in current pom.xml"
          
          echo -e "\n=== Diff Analysis ==="
          DIFF_OUTPUT=$(git diff origin/${{ github.base_ref }} ${{ github.sha }} -- '**/pom.xml')
          if [ -z "$DIFF_OUTPUT" ]; then
            echo "No differences found in any pom.xml files"
          else
            echo "Found differences in pom.xml:"
            echo "$DIFF_OUTPUT"
          fi
          
          echo -e "\n=== Version Pattern Search ==="
          echo "Searching for version changes..."
          # More lenient version search first
          if echo "$DIFF_OUTPUT" | grep -A 2 -B 2 "<version>" > /dev/null; then
            echo "Found version-related changes:"
            echo "$DIFF_OUTPUT" | grep -A 2 -B 2 "<version>" || true
          else
            echo "No version-related changes found in diff"
          fi
          
          # Check for project version changes
          PROJECT_VERSION_CHANGED=$(echo "$DIFF_OUTPUT" | grep -A 1 -B 1 "<version>" | grep -E "^[-+].*<version>" && echo "true" || echo "false")
          
          echo -e "\nProject version changed: $PROJECT_VERSION_CHANGED"
          
          if [ "$PROJECT_VERSION_CHANGED" = "false" ]; then
            echo -e "\n❌ No project version changes detected"
            echo "Current POM content for reference:"
            head -n 20 pom.xml
            echo "::error::Project version in pom.xml has not been updated. Please update the project version."
            exit 1
          else
            echo -e "\n✅ Project version change detected"
            echo "Version change details:"
            echo "$DIFF_OUTPUT" | grep -A 1 -B 1 "<version>"
          fi 