name: POM Version Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check if project version was modified
        run: |
          git config --global --add safe.directory '*'
          
          # Explicitly checkout and compare
          echo -e "\n=== Explicit Branch Setup ==="
          # Save current POM
          cp pom.xml current_pom.xml
          
          # Get base branch version
          git checkout origin/${{ github.base_ref }}
          cp pom.xml base_pom.xml
          
          # Return to PR branch
          git checkout ${{ github.event.pull_request.head.sha }}
          
          echo -e "\n=== Version Comparison ==="
          echo "Base version:"
          grep "<version>" base_pom.xml
          echo "Current version:"
          grep "<version>" current_pom.xml
          
          echo -e "\n=== Direct File Comparison ==="
          if ! diff base_pom.xml current_pom.xml > pom_changes.diff; then
            echo "Found differences between POMs:"
            cat pom_changes.diff
            
            # Check if project version changed
            BASE_VERSION=$(grep -A 0 -B 0 "<version>" base_pom.xml | head -n 1)
            CURRENT_VERSION=$(grep -A 0 -B 0 "<version>" current_pom.xml | head -n 1)
            
            if [ "$BASE_VERSION" != "$CURRENT_VERSION" ]; then
              echo -e "\n✅ Project version change detected"
              echo "From: $BASE_VERSION"
              echo "To: $CURRENT_VERSION"
              exit 0
            fi
          fi
          
          echo -e "\n❌ No project version changes detected"
          echo "::error::Project version in pom.xml has not been updated. Please update the project version."
          exit 1 