name: POM Version Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if version was modified
        run: |
          # Get the diff between base branch and PR
          git fetch origin ${{ github.base_ref }}
          
          # Check if version tag was modified in any pom.xml file
          VERSION_MODIFIED=$(git diff origin/${{ github.base_ref }} ${{ github.sha }} | grep -q "<version>" && echo "true" || echo "false")
          
          if [ "$VERSION_MODIFIED" = "false" ]; then
            echo "::error::No version changes detected in any pom.xml file. Please update the version."
            exit 1
          else
            echo "Version change detected in pom.xml"
          fi 